jobs:
  # --- Noul job de testare ---
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      # TODO 01 - Aici am adăugat comanda de rulare a testelor
      - name: Run tests
        run: go test ./...

  # --- Job-ul existent de compilare ---
  compile:
    runs-on: ubuntu-latest

    # TODO 02 - Aici îi spunem să aștepte după job-ul de "test"
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Compile binary
        run: go build -o myapp
